// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2J1HWmRy02_3civC7PzMCffNlogHCu4w',
    appId: '1:694341470142:web:e1a6a3b865426119d71bef',
    messagingSenderId: '694341470142',
    projectId: 'scooby-app-new',
    authDomain: 'scooby-app-new.firebaseapp.com',
    storageBucket: 'scooby-app-new.firebasestorage.app',
    measurementId: 'G-HGGEXMF78F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPyHjp5iGQ80lTeq6qZPqKFiSC5BV3bJo',
    appId: '1:694341470142:android:c10ef48c5141dae5d71bef',
    messagingSenderId: '694341470142',
    projectId: 'scooby-app-new',
    storageBucket: 'scooby-app-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHpO7i6pwLFxvuQnscOrFY6DNRxBu0DU8',
    appId: '1:694341470142:ios:0e8c15a814b23942d71bef',
    messagingSenderId: '694341470142',
    projectId: 'scooby-app-new',
    storageBucket: 'scooby-app-new.firebasestorage.app',
    iosBundleId: 'com.example.scoobyAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHpO7i6pwLFxvuQnscOrFY6DNRxBu0DU8',
    appId: '1:694341470142:ios:0e8c15a814b23942d71bef',
    messagingSenderId: '694341470142',
    projectId: 'scooby-app-new',
    storageBucket: 'scooby-app-new.firebasestorage.app',
    iosBundleId: 'com.example.scoobyAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2J1HWmRy02_3civC7PzMCffNlogHCu4w',
    appId: '1:694341470142:web:6d4009af2043ab6fd71bef',
    messagingSenderId: '694341470142',
    projectId: 'scooby-app-new',
    authDomain: 'scooby-app-new.firebaseapp.com',
    storageBucket: 'scooby-app-new.firebasestorage.app',
    measurementId: 'G-1CF3JQVD58',
  );
}
